# Generated by Django 3.1.1 on 2020-09-24 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_comment_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
