# Generated by Django 3.1 on 2020-08-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200819_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='currentPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='startingPrice',
            field=models.FloatField(),
        ),
    ]
