# Generated by Django 3.1 on 2020-08-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200820_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imageURL',
            field=models.URLField(blank=True, null='https://www.greekisrael-chamber.gr/images/NoImgUploaded.gif'),
        ),
    ]
