# Generated by Django 3.1 on 2020-08-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200820_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imageURL',
            field=models.URLField(blank=True, default='https://www.greekisrael-chamber.gr/images/NoImgUploaded.gif'),
        ),
    ]
