# Generated by Django 3.1 on 2020-08-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200820_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imageURL',
            field=models.URLField(blank=True, default='https://img.icons8.com/ios/500/000000/no-image.png'),
        ),
    ]
