# Generated by Django 3.1 on 2020-08-20 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200820_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='Listing',
            new_name='listing',
        ),
    ]
