# Generated by Django 3.1 on 2020-08-20 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200821_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Listing',
            new_name='listing',
        ),
    ]
