# Generated by Django 3.1 on 2020-08-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20200827_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Books', 'Books'), ('Technology', 'Technology'), ('Home & Kitchen', 'Home & Kitchen'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Beauty & Personal Care', 'Beauty & Personal Care'), ('Fashion', 'Fashion'), ('Other', 'Other')], max_length=64),
        ),
    ]
