# Generated by Django 3.1 on 2020-08-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20200828_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='startingPrice',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='currentPrice',
        ),
    ]
