# Generated by Django 3.1 on 2020-08-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20200828_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Books', 'Books'), ('Technology', 'Technology'), ('Home & Kitchen', 'Home & Kitchen'), ('Sports & Outdoor', 'Sports & Outdoor'), ('Beauty & Personal Care', 'Beauty & Personal Care'), ('Fashion', 'Fashion'), ('Other', 'Other')], max_length=64),
        ),
    ]
