# Generated by Django 3.1.1 on 2020-09-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200926_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='enrolled',
            field=models.ManyToManyField(blank=True, related_name='students', to='courses.Course'),
        ),
    ]
