# Generated by Django 3.1.1 on 2020-09-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200926_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.URLField(blank=True, default='https://img.icons8.com/ios/500/000000/no-image.png'),
        ),
    ]
