# Generated by Django 3.1.1 on 2020-09-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='topic',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Business', 'Business'), ('Finance', 'Finance'), ('Design', 'Design'), ('Fotografie', 'Fotografie'), ('Marketing', 'Marketing'), ('Music', 'Music'), ('Health', 'Health')], max_length=70),
        ),
    ]
