# Generated by Django 3.1.1 on 2020-09-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20200927_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseSummary',
            field=models.TextField(default='To Add', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='effort',
            field=models.CharField(choices=[('0–6 hours per week', '0–6 hours per week'), ('7–18 hours per week', '7–18 hours per week'), ('19–30 hours per week', '19–30 hours per week')], default='7–18 hours per week', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default='English', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='lengthWeeks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Introductory', 'Introductory'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Intermediate', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('Self-paced on your time', 'Self-paced on your time'), (' Instructor-led on a course schedule', ' Instructor-led on a course schedule')], default='Self-paced on your time', max_length=150),
            preserve_default=False,
        ),
    ]
