# Generated by Django 3.1.1 on 2020-09-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20200928_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='newfield',
            field=models.IntegerField(default=0),
        ),
    ]
