# Generated by Django 3.1.1 on 2020-09-27 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_newfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='newfield',
        ),
    ]
