# Generated by Django 3.1.1 on 2020-09-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20200928_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('Self-paced on your time', 'Self-paced on your time'), (' Instructor-led schedule', ' Instructor-led schedule')], max_length=150),
        ),
    ]
