# Generated by Django 3.1.1 on 2020-09-29 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20200929_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='summary',
            new_name='outline',
        ),
    ]
